apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kube-autoscaler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  template:
    metadata:
      labels:
        k8s-app: kube-autoscaler
    spec:
      containers:
      - name: autoscaler
        image: blaac/autoscaler:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: config
          mountPath: /conf.yml
          subPath: conf.yml
      serviceAccount: autoscaler
      serviceAccountName: autoscaler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        configMap:
          name: autoscaler-config
